# Generated by Django 5.1.6 on 2025-10-10 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("daily_kcal", models.PositiveIntegerField()),
                (
                    "protein_target_g",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("fat_target_g", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carb_target_g", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "created_from_goal_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("kcal_target", models.PositiveIntegerField()),
                (
                    "protein_target_g",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("fat_target_g", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carb_target_g", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="planning.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("meal_plan", "date")},
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "breakfast"),
                            ("lunch", "lunch"),
                            ("dinner", "dinner"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "servings",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "eaten_servings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("marked_eaten_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planning.planday",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_type", "id"],
            },
        ),
    ]
